"""Guards the ORM/migration contract: a model change without a matching
Alembic migration (or vice versa) fails here instead of in production."""

import asyncio

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected

from app.core.config import Settings
from app.db.migrations import alembic_config

pytestmark = pytest.mark.anyio


async def test_database_is_at_head_and_matches_models(app):
    # The `app` fixture has already started up, i.e. run `upgrade head`.
    cfg = alembic_config(Settings().database_url)
    assert ScriptDirectory.from_config(cfg).get_current_head() == "0001"
    try:
        await asyncio.to_thread(command.check, cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"models and migrations differ; run `alembic revision --autogenerate`:\n{exc}")
